name: termbox_test
on: [push, pull_request]
jobs:
  termbox_test_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run:                             make clean test
      - run: CFLAGS='-UTB_OPT_TRUECOLOR' make clean test # non-truecolor
      - run: CFLAGS='-UTB_OPT_EGC'       make clean test # non-egc
